In [3]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [45]:
X=np.array([
    [[25,25,25],[0,0,0],[0,0,0]],
    [[25,0,0],[25,0,0],[25,0,0]],
    [[75,75,75],[75,75,75],[75,75,75]]
           ])

In [46]:
X.shape

(3, 3, 3)

In [47]:
X_centered  = X - X.mean(axis = 0)

In [48]:
X_centered

array([[[-16.66666667,  -8.33333333,  -8.33333333],
        [-33.33333333, -25.        , -25.        ],
        [-33.33333333, -25.        , -25.        ]],

       [[-16.66666667, -33.33333333, -33.33333333],
        [ -8.33333333, -25.        , -25.        ],
        [ -8.33333333, -25.        , -25.        ]],

       [[ 33.33333333,  41.66666667,  41.66666667],
        [ 41.66666667,  50.        ,  50.        ],
        [ 41.66666667,  50.        ,  50.        ]]])

In [49]:
U ,s, Vt = np.linalg.svd(X_centered)

In [50]:
Vt

array([[[ 0.69742872,  0.50675101,  0.50675101],
        [-0.71665416,  0.49315658,  0.49315658],
        [ 0.        , -0.70710678,  0.70710678]],

       [[ 0.28037722,  0.67874466,  0.67874466],
        [-0.9598899 ,  0.19825663,  0.19825663],
        [ 0.        , -0.70710678,  0.70710678]],

       [[-0.50380256, -0.61081216, -0.61081216],
        [-0.86381884,  0.35624221,  0.35624221],
        [ 0.        , -0.70710678,  0.70710678]]])

In [51]:
Vt[0][1]

array([-0.71665416,  0.49315658,  0.49315658])

In [52]:
c1 = Vt[0][0]
c2 = Vt[0][1]

In [53]:
W2 = Vt[0,:2].T

In [54]:
X2D = X_centered @W2

In [55]:
X2D

array([[[-20.06966223,   3.72495967],
        [-48.5851747 ,  -0.76935694],
        [-48.5851747 ,  -0.76935694]],

       [[-45.40721295, -20.93286918],
        [-31.14945672, -18.68571087],
        [-31.14945672, -18.68571087]],

       [[ 65.47687518,  17.2079095 ],
        [ 79.73463142,  19.45506781],
        [ 79.73463142,  19.45506781]]])

In [73]:
pca = PCA(n_components=2)

In [71]:
data_2d = np.array([features_2d.flatten() for features_2d in X])

In [72]:
data_2d

array([[25, 25, 25,  0,  0,  0,  0,  0,  0],
       [25,  0,  0, 25,  0,  0, 25,  0,  0],
       [75, 75, 75, 75, 75, 75, 75, 75, 75]])

In [74]:
X2D = pca.fit_transform(data_2d)

In [75]:
pca.explained_variance_ratio_

array([0.95588235, 0.04411765])

In [76]:
pca.explained_variance_

array([13541.66666667,   625.        ])

# Choosing right number of Dimensions

In [77]:
from sklearn.datasets import fetch_openml

In [78]:
mnist = fetch_openml('mnist_784', as_frame=False)
X_train, y_train = mnist.data[:60_000], mnist.target[:60_000]

In [79]:
X_test, y_test = mnist.data[60_000:],mnist.target[60_000:]

In [80]:
pca = PCA()
pca.fit(X_train)

PCA()

In [81]:
pca.explained_variance_ratio_

array([9.70466436e-02, 7.09592406e-02, 6.16908876e-02, 5.38941949e-02,
       4.86879702e-02, 4.31223132e-02, 3.27192995e-02, 2.88389545e-02,
       2.76202940e-02, 2.35700055e-02, 2.10918962e-02, 2.02299108e-02,
       1.71581820e-02, 1.69211143e-02, 1.57864128e-02, 1.48295261e-02,
       1.32456095e-02, 1.27689737e-02, 1.18726294e-02, 1.15268370e-02,
       1.06616621e-02, 1.00671337e-02, 9.53573327e-03, 9.12543746e-03,
       8.83404692e-03, 8.39319141e-03, 8.12578809e-03, 7.86366084e-03,
       7.44733102e-03, 6.90859128e-03, 6.58093773e-03, 6.48147870e-03,
       6.02615030e-03, 5.86582188e-03, 5.70021474e-03, 5.43627771e-03,
       5.05786416e-03, 4.87858604e-03, 4.81429342e-03, 4.72266326e-03,
       4.56746921e-03, 4.44836012e-03, 4.18501329e-03, 3.98215339e-03,
       3.84974607e-03, 3.75103387e-03, 3.62008852e-03, 3.51591277e-03,
       3.40058205e-03, 3.21874467e-03, 3.19017051e-03, 3.12804939e-03,
       2.95982668e-03, 2.88954600e-03, 2.84130398e-03, 2.71435811e-03,
      

In [82]:
cumsum = np.cumsum(pca.explained_variance_ratio_)

In [83]:
cumsum

array([0.09704664, 0.16800588, 0.22969677, 0.28359097, 0.33227894,
       0.37540125, 0.40812055, 0.4369595 , 0.4645798 , 0.4881498 ,
       0.5092417 , 0.52947161, 0.54662979, 0.56355091, 0.57933732,
       0.59416685, 0.60741246, 0.62018143, 0.63205406, 0.6435809 ,
       0.65424256, 0.66430969, 0.67384542, 0.68297086, 0.69180491,
       0.7001981 , 0.70832389, 0.71618755, 0.72363488, 0.73054347,
       0.73712441, 0.74360589, 0.74963204, 0.75549786, 0.76119807,
       0.76663435, 0.77169222, 0.7765708 , 0.7813851 , 0.78610776,
       0.79067523, 0.79512359, 0.7993086 , 0.80329076, 0.8071405 ,
       0.81089154, 0.81451162, 0.81802754, 0.82142812, 0.82464686,
       0.82783703, 0.83096508, 0.83392491, 0.83681446, 0.83965576,
       0.84237012, 0.84506533, 0.84765006, 0.85018776, 0.85263557,
       0.85504063, 0.85743326, 0.85973735, 0.86195267, 0.86408988,
       0.86616213, 0.86819256, 0.87016038, 0.87208891, 0.87397523,
       0.875845  , 0.87765583, 0.87943146, 0.88118044, 0.88283

In [84]:
d = np.argmax(cumsum >=0.95) + 1

In [86]:
d # 154 is the optimal componets for this dataset.

154

In [87]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import make_pipeline

In [88]:
clf = make_pipeline(PCA(random_state=42),
                   RandomForestClassifier(random_state=42))

In [96]:
param_distrib = {"pca__n_components": np.arange(10,80),
                "randomforestclassifier__n_estimators": np.arange(50,500)}

In [97]:
rnd_search = RandomizedSearchCV(clf,param_distrib, n_iter=10,cv=3,random_state=42)

In [ ]:
rnd_search.fit(X_train[:1000],y_train[:1000])

In [99]:
rnd_search.best_params_

{'randomforestclassifier__n_estimators': 465, 'pca__n_components': 23}

# Incremental PCA

In [100]:
from sklearn.decomposition import IncrementalPCA
n_batches = 100

In [101]:
inc_pca = IncrementalPCA(n_components=154)
for X_batch in np.array_split(X_train, n_batches):
    inc_pca.partial_fit(X_batch)

In [102]:
X_reduced = inc_pca.transform(X_train)

In [104]:
X_reduced.shape

(60000, 154)

# Random Projection 

In [105]:
from sklearn.random_projection import johnson_lindenstrauss_min_dim
m ,e = 5_000, 0.1
d = johnson_lindenstrauss_min_dim(m,eps=e)
d

7300

In [109]:
n = 20_000
np.random.seed(42)
P = np.random.randn(d,n) / np.sqrt(d)

In [110]:
P.shape

(7300, 20000)

In [111]:
X = np.random.randn(m,n) 

In [112]:
X_reduced = X @ P.T

In [114]:
X_reduced.shape

(5000, 7300)

In [116]:
from sklearn.random_projection import GaussianRandomProjection

gaussion_rnd_proj =  GaussianRandomProjection(eps = e, random_state=42)

In [118]:
X_reduced = gaussion_rnd_proj.fit_transform(X)

In [120]:
X_reduced.shape

(5000, 7300)

# Locally Linear Embedding - Mainfold Learning

In [121]:
from sklearn.datasets import make_swiss_roll
from sklearn.manifold import LocallyLinearEmbedding

In [126]:
X_swiss,t = make_swiss_roll(n_samples=1000, noise=0.2, random_state=42)
lle = LocallyLinearEmbedding(n_components=2, n_neighbors=10, random_state=42)

In [127]:
x_unrolled = lle.fit_transform(X_swiss)

In [128]:
x_unrolled.shape

(1000, 2)

In [129]:
X_swiss.shape

(1000, 3)